modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.227,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecolonies"
type="required"
versionRange="[1.1.1300,)"
ordering="AFTER"
side="BOTH"

# Sable is treated as required for physical container gameplay, but compile-time access is through Sable Companion.
[[dependencies.${mod_id}]]
modId="sable"
type="required"
versionRange="[1.1.3,)"
ordering="AFTER"
side="BOTH"
